name: pycalphad-fitting

dependencies:
  - anaconda
  - python
  - numpy
  - scipy
  - matplotlib
  - xray
  - tinydb
  - autograd
  - numba
  - pymc
  - pip:
    - git+https://github.com/richardotis/pycalphad.git@develop#egg=pycalphad-develop
    - corner

channels:
  - richardotis
  - defaults
